### ISSUE TITLE
Unable to finish the workout

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#69] opened 2021-02-28 17:58 UTC
- [X] I have read the [contribution guidelines](https://github.com/noahjutz/Splitfit/blob/master/CONTRIBUTING.md).
- [X] I am using the [latest version](https://github.com/noahjutz/Splitfit/releases).

**Describe the bug**
As you can see in the following screencast I'm unable to finish the current workout without starting a new one!

**Screenshots / Screen recordings**

https://user-images.githubusercontent.com/284547/109428309-9ea67180-7a07-11eb-8f37-5f223b4bd21e.mp4

**Smartphone (please complete the following information):**
 - Android version: Android 10

**Comment by noahjutz** [comment] 2021-02-28 18:03
Duplicate of #67

**Closed as completed by noahjutz** 2021-02-28 18:03 UTC
Labels: bug

**Comment by noahjutz** [comment] 2021-02-28 19:01
@mbnoimi I've created a new release that fixes the bug. https://github.com/noahjutz/Splitfit/releases
